pipeline{
	environment {
		mavenHome = tool 'maven'
		}

	agent any
	stages{
		stage ('compile stage'){
			steps{
			
			  	bat 'maven clean compile'
			  	
			}
		}
		stage ('Testing Stage'){
			steps{
			
			  	bat 'maven test'
			  	
			}
		}
		stage ('Deploy stage'){
			steps{
			
			  	bat 'maven deploy'
			  	
			}
		}
	}
}